language: objective-c
osx_image: xcode7.3
branches:
  only:
    - master
before_install:
  - gem install xcpretty
script:
- set -o pipefail
- xcodebuild -project Example/VLCRemoteKitExample.xcodeproj -scheme VLCRemoteKitTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO test | xcpretty -c
